name: Build APK

on:
  push:
    branches:
      - main  # Executa o build sempre que houver push na branch main
  pull_request:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"  # Versão do Flutter (ajuste conforme necessário)

      - name: Instalar dependências
        run: flutter pub get

      - name: Compilar APK release
        run: flutter build apk --release

      - name: Upload APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
